apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-app
  labels:
    app: {{ include "test-app.name" . }}
spec:
  selector:
    app: {{ include "test-app.name" . }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: LoadBalancer ##to expose the application externally