apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-db
  labels:
    app: {{ include "test-app.name" . }}-db
spec:
  selector:
    app: {{ include "test-app.name" . }}-db
  ports:
    - port: 5432 
      targetPort: 5432  
  type: ClusterIP 